environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      TARGET: x86_64-pc-windows-msvc
    - PYTHON: "C:\\Python37-x64"
      TARGET: x86_64-pc-windows-msvc
    - PYTHON: "C:\\Python38-x64"
      TARGET: x86_64-pc-windows-msvc

branches:
  only:
  - master
  - /lts-.*/

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -e .[test] --upgrade --upgrade-strategy eager"

build: false

test_script:
  - "%PYTHON%\\python.exe -m snips_nlu download-all-languages"
  - "%PYTHON%\\python.exe -m snips_nlu download-language-entities fr"
  - "%PYTHON%\\python.exe -m snips_nlu download-language-entities en"
  - "%PYTHON%\\python.exe -m unittest discover"
  - "%PYTHON%\\python.exe snips_nlu_samples/sample.py"
