os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36,docs-html
    - python: 3.6
      env: TOXENV=integration-test
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27

install: python -m pip install tox codecov

script: tox

after_success:
  - tox -e coverage-report
  - codecov

cache: pip
